### PR TITLE
Move to collective?  Also, fix svn switch handling.

### PR DESCRIPTION
**Pull request by rpatterson**
If you like, we can just leave this in the collective, in which case you can ignore this pull request and just give me PyPI release rights.  Otherwise, it would be great if you could merge this and cut a new release.

I've fixed svn switch handling and updated the tests.  I've tested this locally and it works with a real-world code base with lots of refactoring changes between the branch and trunk.

### CODE REVIEW

**Comment by tomster** [comment]
ross, i've added you as maintainer on PyPI, feel free to make a release, although i strongly would prefer if there'd be a test for your fix. i'm all for keeping this in the collective.

**Comment by rpatterson** [comment]
Ok, well I can just work from a develop egg locally with the fix and wait to release until someone has time to add a test.  Which would you prefer?  Cut a release now or wait until someone has the time to add that test?

**Comment by tomster** [comment]
fuck it, make a release :)

**Comment by rpatterson** [comment]
Ugh, sorry Tom, I have username hell and I should have told you my username on PyPI is `rpatterson`, not `rossp` as it is on plone.org.  Can you change the PyPI maintainer from `rossp` to `rpatterson`?

**Comment by tomster** [comment]
done

**Comment by rpatterson** [comment]
...and done.  :-)
http://pypi.python.org/pypi/git-svn-helpers/0.9

**Pull request merged**
